export const CREATE_CARD_REQUEST: "CREATE_CARD_REQUEST" = "CREATE_CARD_REQUEST"
export const CREATE_CARD_FAILED: "CREATE_CARD_FAILED" = "CREATE_CARD_FAILED"
export const CREATE_CARD_SUCCESS: "CREATE_CARD_SUCCESS" = "CREATE_CARD_SUCCESS"

export const DELETE_CARD_REQUEST: "DELETE_CARD_REQUEST" = "DELETE_CARD_REQUEST"
export const DELETE_CARD_FAILED: "DELETE_CARD_FAILED" = "DELETE_CARD_FAILED"
export const DELETE_CARD_SUCCESS: "DELETE_CARD_SUCCESS" = "DELETE_CARD_SUCCESS"

export const BUY_CARD_REQUEST: "BUY_CARD_REQUEST" = "BUY_CARD_REQUEST"
export const BUY_CARD_FAILED: "BUY_CARD_FAILED" = "BUY_CARD_FAILED"
export const BUY_CARD_SUCCESS: "BUY_CARD_SUCCESS" = "BUY_CARD_SUCCESS"

export const SET_NOTIFICATION: "SET_NOTIFICATION" = "SET_NOTIFICATION"